language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - ./scripts/install-deps.sh

script:
  - ./scripts/run-tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
